POST http://localhost:5000/signup
Content-Type: application/json

{
    "name":"Sergio",
    "email":"sergio@wap.com",
    "password":"123sergio"
}

###SIGN IN REQUEST

POST http://localhost:5000/signin
Content-Type: application/json

{
    "email":"sergio@wap.com",
    "password":"123sergio"
}